library(shiny)
library(ggplot2)
library(plotly)

co2_data <- read.csv("owid-co2-data.csv")
co2_data$year <- as.factor(co2_data$year)

ui <- navbarPage(
  title = "My Shiny App",
  tabPanel("Page 1",
           h2("Introduction"),
           p("This assignment uses the above dataset to explore trends in CO2 emissions using data compiled by Our World In Data. The features that I have chosen to analyse are country, year, and cumulative_co2. This is because it gives a holistic view on how the co2 levels have varied by country over time. "),
           p(),
           p("In specific, I will be analysing how does the cumulative CO2 level change based on the country and year recorded. By definition cumulative_co2 implies Total cumulative production-based emissions of carbon dioxide (CO₂), excluding land-use change, since the first year of data availability, measured in million tonnes. This is based on territorial emissions, which do not account for emissions embedded in traded goods. Therefore, the graph that I depict will represent an interactive line chart to represent the cumulative co2 level grouped by country over a period of time."),
           p(),
           p("In addition to these analyses it is important to understand where the data has come from and how it was collected and generated. To my knowledge, the data is collected by Our World in Data and is usually collected/ generated by research articles, specialized institutions, or official government sources.Possible limitations to this project is that the data is too vast. Although it covers data from recent years, I found it slightly tedious to work through really years of data. Another limitation is that this dataset does not represent any other paramenter that could explain different level of co2 emissions. Another parameter like number of vehicles each year could help us make a pattern on the cumulative co2 levels."),

           h2("Summary and Data"),
           h4("What is the average value of cumulative_co2 across all countries?"),
           p(" - The average value of cumulative_co2 across all countries is, 10834.1916138779"),
           h4("Where is the cumulative_co2 highest or lowest?"),
           p(" - The highest value of co2 level across all countries across different years is, 1736930.125"),
           p(" - The lowest value of co2 level across all countries across different years is, 0"),
           h4("How much has cumulative_co2 changed over the last 20 years?"),
           p("To understand how the variable - cumulative_co2-  has changed over 41 years, I compute how it has changed from 1980 to 2000 and from 2001 to 2021"),
           p(" - The difference of cumulative_co2 between years 1980 and 2000 is "),
           tableOutput("diff1"),
           
           p("The difference of cumulative_co2 between years 2001 and 2021 is "),
           tableOutput("diff2")
  ),
  
  tabPanel("Page 2",
           h2("Cumulative Co2 Levels"),
           plotlyOutput("plot"),
           p("The above line chart gives an accurate representation of the cumulative co2 levels across different countries over a period of time. This interative plot has a list of countries to the right which when double-clicked will represent the given pattern for that specific country."),
           p("Some patterns that I can see is that the cumulative-co2 levels for all the countries rises as time increases. Year-by-year we can se a slight increase in the level as the slope of the line chart increases")
  )
)